// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV6tbismxvUTulcEIroYbyXZrCtK_nrnQ',
    appId: '1:140513486227:web:9c7998f483c3e21166b466',
    messagingSenderId: '140513486227',
    projectId: 'bhtapp-ab3ac',
    authDomain: 'bhtapp-ab3ac.firebaseapp.com',
    storageBucket: 'bhtapp-ab3ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbdTClqe9zZVOYXyDq-iz-3dosDId69pY',
    appId: '1:140513486227:android:9c58965fcda9962b66b466',
    messagingSenderId: '140513486227',
    projectId: 'bhtapp-ab3ac',
    storageBucket: 'bhtapp-ab3ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwEIMg4a8RmK1ajFM2J3hgXjh4al7Jsx4',
    appId: '1:140513486227:ios:5aea7357164e919f66b466',
    messagingSenderId: '140513486227',
    projectId: 'bhtapp-ab3ac',
    storageBucket: 'bhtapp-ab3ac.firebasestorage.app',
    iosBundleId: 'com.example.rasadharmaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwEIMg4a8RmK1ajFM2J3hgXjh4al7Jsx4',
    appId: '1:140513486227:ios:5aea7357164e919f66b466',
    messagingSenderId: '140513486227',
    projectId: 'bhtapp-ab3ac',
    storageBucket: 'bhtapp-ab3ac.firebasestorage.app',
    iosBundleId: 'com.example.rasadharmaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV6tbismxvUTulcEIroYbyXZrCtK_nrnQ',
    appId: '1:140513486227:web:1bd95a670af596b766b466',
    messagingSenderId: '140513486227',
    projectId: 'bhtapp-ab3ac',
    authDomain: 'bhtapp-ab3ac.firebaseapp.com',
    storageBucket: 'bhtapp-ab3ac.firebasestorage.app',
  );

}